### ISSUE TITLE
Mailbox names need to be quoted

### ISSUE THREAD

**Issue by davidgiven** [mkawalec/imap#17]
I see that mailbox names aren't quoted or otherwise escaped while the command is being constructed; this fails for mailboxes whose names contain spaces or other characters which aren't valid in an IMAP atoms.

e.g.:

IMAP.select conn "[Gmail]/All Mail"
-> fails with a BAD "Could not parse command".

IMAP.select conn "\"[Gmail]/All Mail\""
-> works.

**Comment by mkawalec** [comment]
implemented in https://github.com/mkawalec/imap/commit/49a70b81317275ca3f0f0e25fd5d0b5fa50a4bc8
