### ISSUE TITLE
Problems with 32-bit Int

### ISSUE THREAD

**Issue by davidgiven** [mkawalec/imap#18]
So this is a bit nitpicky, but...

The CONDSTORE extension defines that the modseq value is a 64-bit int. However, `UntaggedResult` uses `HighestModSeq Int`, and there are Haskell systems where Ints are 32-bits long, which would cause... actually, I'm not sure what would happen, but it would be bad.

I don't know if this affects any real-life systems, but you should be aware.

**Comment by mkawalec** [comment]
fixed in https://github.com/mkawalec/imap/commit/04ece624584ae41fd2858f8c24537b5c6c309be7, just to be protected and for consistency used Integers everywhere
