### ISSUE TITLE
Capabilities can contain +

### ISSUE THREAD

**Issue by cocreature** [mkawalec/imap#5]
At least the [LITERAL+](https://tools.ietf.org/html/rfc2088) capabilty contains a `+` and that breaks your parsing, since you only accept things matching `isAtomChar` and `+` is not among those.

I am not sure if it makes sense to modify `isAtomChar` or add a special case for the parsing of capabilities.

**Comment by mkawalec** [comment]
This was an error in the way I was handling atom characters (too few were accepted). Should be fixed now, latest updated version pushed to Hackage.

**Comment by cocreature** [comment]
Thanks, that works now.
