### ISSUE TITLE
build an IMAPbackup tool

### ISSUE THREAD

**Issue by thkoch2001** [mkawalec/imap#6]
I need a tool to one-way sync an IMAP account to my home backup server. Every time the sync job runs it should update the local backup to reflect the state of the remote account. Local changes are not made.

I tried offlinesync and mbsync for this task but both programs fail when a folder gets deleted and recreated.

If you would write such a tool on top of your library I would be happy to test and use it and report back all issues I find.

Thanks for consideration.

**Comment by mkawalec** [comment]
Sounds like a good idea. I'll have to cut out (and correct at places) email parsing from https://github.com/mkawalec/email into a separate library next. Once that is done, it should be very simple to glue this and an email parser together to backup email to a disk. 

@thkoch2001: What format would you like to have as an output? Maildir, mailbox or a DB output?

**Comment by thkoch2001** [comment]
After the sync I just do a BTRFS snapshot. So Maildir would be best. 

Thank you very much for considering this! I do not really understand why email parsing would be needed for this tool? For the backup tool the emails are just files, aren't they?

**Comment by mkawalec** [comment]
Oh, you mean just a straight "let's take these messages from a mailserver"? That looks easily doable, but I want that email parsing done first, so if you or someone else want to write it, go ahead:) Otherwise, I'll get to it once I'm done with the email parser.

**Comment by thkoch2001** [comment]
Yes, as easy as it gets. But it seems with IMAP everything gets complicate. The one and only requirement is that the tool would backup all information of my IMAP backup so that I could upload the backup to a new server and it would be as before.

**Comment by mkawalec** [comment]
I've decided I will not implement this, want to focus solely on the email client. In the meantime, there is a new version of offlineimap being written, which could be of interest to you: https://github.com/OfflineIMAP/imapfw
